[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Admin routes
[[redirects]]
  from = "/ErvinAdmin/*"
  to = "/ErvinAdmin/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"